import type { Metadata } from "next";
import { Inter, Manrope, DM_Sans } from "next/font/google";

import "./globals.css";
import { ApolloWrapper } from "../providers/ApolloProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ApolloWrapper>
        <body
          className={`${inter.variable} ${manrope.variable} ${dmSans.variable} font-dm-sans antialiased`}
        >
          {children}
        </body>
      </ApolloWrapper>
    </html>
  );
}
